const siteContent = {
    "en": {
        "nav": {
            "home": "Home",
            "dashboard": "The Language of Video Games"
        },
        "controls": {
            "music_on": "Turn on music",
            "music_off": "Turn off music",
            "theme": "Light/Dark",
            "lang": "Change to Polish 🇵🇱",
            "attribution": "Playing: \"Bolero\" by Maurice Ravel performed by Lamoureux Orchestra"
        },
        "about": {
            "title": "About Me",
            "p1": "Hello! I'm a 21 year old uni student, currently right at the end of my <a href='https://sylabusy.agh.edu.pl/pl/1/2/19/1/1/0/81'>social informatics</a> undergrad program. For a loooooooooooong WHILE i've been interested in the way people interact with computers - I spent quite a bit of time in the peripheral rabbit hole, to the point where I made <a href='https://github.com/Kamillon125/bonk/blob/gh-pages/index.md'>my own keyboard layout</a> (!!! it's extremely useless BUT neat!). Peripherals are not all I'm interested in though, for a while there I was really into handheld video game consoles (and how they've evolved overtime), which, once again is very useless, but also quite neat! I love linguistics, too, and specifically the part of linguistics that relates to learning languages. I know Polish, English (C2-ish?), enough Ukrainian to have read a book in the language back in 2024 (Лаовай by Kateryna Kulyk), and have been flirting with a little bit of Italian recently. I'm also on the way to publishing a scientific article on language acquisition in video games, which should be out by the end of 2026. I used to be a MASSIVE Nintendo fan (a big mistake) and have played basically every single Pokemon and Zelda game that exists. I still love these franchises, especially the atmosphere of some of these games (completely agree with <a href='https://www.youtube.com/watch?v=xI43wgrPP28'>Internet Pitstop</a> on YouTube as far as atmosphere in gaming) If you want to know more about my professional work stuff, here's my <a href='https://www.linkedin.com/in/kamil-niewiarowski/'>LinkedIn</a>, you won't find that type of stuff on this website."
        },
        "computer": {
            "title": "Computer stuff",
            "p1": "After many years of trying to quit Windows I think i've finally managed to do it. I really don't like how MS Windows is just getting worse and worse - like look, I really don't want Copilot being shoved down my throat, and I hate how Windows uses my personal data more than I use Windows as an OS. Like, I still have it somewhere on my PC, but that's only in case I ever come across software I NEED to open but can't on Linux, and 100% of my daily computer use is on Linux. Which, right now I'm using <a href='https://cachyos.org/'>CachyOS</a> with the <a href='https://www.gnome.org/'>Gnome Desktop Environment</a>. I tried <a href='https://system76.com/cosmic'>COSMIC</a>, but it was waaaay too new and some things didn't work on it, and I also tried <a href='https://kde.org/'>KDE</a>, which was good but honestly felt very bland and boring. Besides that, at some point in the past I tried tiling window managers (<a href='https://github.com/WillPower3309/swayfx'>swayfx</a>), but like, honest to God, configuring EVERYTHING on your own and not even having a notification daemon out of the box was so annoying, that i'd rather just slightly adjust Gnome to fit my needs. I do recommend Linux - the vast majority of things \"just works\", even most video games work on my Nvidia GPU, and, honestly, as for the video games that don't work (such as Valorant), it's a selling point for Linux that you can't play Val on it."
        },
        "games": {
            "title": "Video games",
            "p1": "I've been playing video games ever since I was a small kid, and I do have some specific memories that I particularly cherish. And look, I'm not talking about some incredible achievements in competitive games, cause even if we consider being top 1 in the world a success, from my point of view that memory just disappeared and doesn't matter to me at all. What matters, however, are memories related to very specific situations in my life. I vividly remember playing through my first Pokemon game (Pokemon X) during christmas, and how right after Christmas Eve I was trying to catch Mewtwo - Venusaur, my absolute GOAT, made it so easy. I remember playing Tears of The Kingdom for the first time during my high school finals, and that game was SOOOO GOOD, that it singlehandedly made me interested in Zelda game and it was why I spent the next 2 years trying to play every single Zelda game I could find. And then, I also remember first playing Minecraft when I was 7 - that's when I built my first Minecraft base inside a mountain. I have one conclusion from all this - my favourite video games are not the best video games I've played, but instead the video games I played during very memorable parts of my life."
        },
        "music": {
            "title": "Music",
            "p1": "The more time I spend on this planet, the more I like listening to rap, and I'm not sure what to do with this condition. Recently I've been listening to quite a bit of <a href='https://tacohemingway.com'>Taco Hemingway</a>, especially his newest album - <a href='https://open.spotify.com/album/6sIS875clsC3HlnRhIzXWL'>\"LATARNIE WSZĘDZIE DAWNO ZGASŁY\"</a> and the thing I like the most about it is that every single time I listen to it I can pick up on some new things I didn't pick up on before. Although, to be perfectly honest, I listen to music very little, basically only whenever I'm taking the bus home or to uni, so I don't spend that much time on rap either."
        },
        "dashboard": {
            "series": "Series",
            "year": "Year",
            "source": "Source",
            "type": "Type",
            "completeness": "Completeness",
            "voiceover": "Voiceover",
            "total_lines": "Total Lines Extracted",
            "word_count": "Word Count",
            "sentence_count": "Sentence Count",
            "tier1_title": "1. Learning Utility",
            "tier1_desc": "Bar charts comparing the video game's amount of unique words and unique learned words (those that appeared 12 or more times) to the corpus' median.",
            "unique_vocab": "Unique Vocab",
            "learned_vocab": "Learned Vocab",
            "learned_b2": "B2 Learned",
            "learned_c1": "C1 Learned",
            "learned_c2": "C2 Learned",
            "tier2a_title": "2A. Syntactic & Lexical Metrics",
            "tier2a_desc": "Different metrics measuring syntactic (grammatical) and lexical (word-related) things.",
            "pv_1k": "Phrasal Verbs (per 1k)",
            "slang_dens": "Slang Density",
            "lex_with": "Lexical Density (w/ Proper)",
            "lex_without": "Lexical Density (w/o Proper)",
            "passives": "Passives/Sentence",
            "subordinates": "Subordinates/Sentence",
            "conditionals": "Conditionals/Sentence",
            "tier2b_title": "2B. CEFR Level Distribution",
            "tier2b_desc": "A bar chart with two axes...",
            "tier3a_title": "3A. Thresholds",
            "tier3a_desc": "What language level you need to be at to either comprehend (95% known words, Laufer (1995)) or acquire new words (98% known words, Hu & Nation, 2000). Though it stands to reason that these thresholds may be lower in video games (which you can rely on context more than in books)",
            "tier3b_title": "3B. CEFR Sentences",
            "tier3b_desc": "I used huggingface.co/dksysd/cefr-classifier to classify each sentence into its own CEFR level. This classifier does its job reasonably, 89.7% accuracy on a parallel corpus dataset.",
            "level": "Level",
            "count": "Count",
            "tier3c_title": "3C. Readability (L1)",
            "tier3c_desc": "Various readability metrics for the game's text, more important for people whose first language is english, but still quite interesting.",
            "tier4a_title": "4A. Top Counts",
            "tier4a_desc": "Shows the most-often-appearing lemmas, bigrams, phrasal verbs and combos of verb-preposition and adjective-noun.",
            "top_lemmas": "Top Lemmas",
            "top_bigrams": "Top Bigrams",
            "verb_prep": "Verb-Preposition",
            "adj_noun": "Adjective-Noun",
            "phrasal_verbs": "Phrasal Verbs",
            "tier4b_title": "4B. OOV & Outliers",
            "tier4b_desc": "Out of vocabulary words are essentially words that appeared in the game but were not in the english dictionary I used (spaCy en_core_web_md).",
            "oov_rate": "OOV Rate",
            "top_10_oov": "Top 10 OOV",
            "toggle_oov": "Toggle Full OOV List",
            "global_summary": "In total: <strong>702,862</strong> lines extracted from <strong>56</strong> games, analysed <strong>1,333,761</strong> sentences made up of <strong>9,029,776</strong> words.",
            "methodology_title": "Methodology & Notes",
            "methodology_desc": "All video game cover art, titles, and associated imagery are the property of their respective publishers and developers..."
        },
        "tooltips": {
            "placeholder": "[Tooltip explanation placeholder. Edit this in content.js]",
            "source": "Data gathered from the Video Game Dialogue Corpus (Rennick & Roberts, in press). Source is where the dialogue data was scraped from.",
            "type": "Data gathered from the Video Game Dialogue Corpus (Rennick & Roberts, in press). Type is the type of the source, whether it was fan-made, official, scraped from actual game files, etc.",
            "completeness": "Data gathered from the Video Game Dialogue Corpus (Rennick & Roberts, in press). Completeness is how complete the dialogue dataset is. Ranges from sample (only a sample of the dialogues) and in progress, all the way to high and complete.",
            "voiceover": "Data gathered for this project - describes whether the game had some form of a voiceover, which may boost copmrehension, in line with the dual coding theory (Mayer & Sims, 1994). Values range from none and minimal all the way to full. ",
            "total_lines": "The amount of total lines extracted from the game's dataset, not including things like out-of-game descriptions by walkthrough makers (if a walkthrough was the source).",
            "word_count": "The amount of total words in the game, including all the dialogue text.",
            "sentence_count": "The amount of sentences in the game, as detected by spaCy's Sentencizer.",
            "unique_vocab": "The amount of unique vocabulary in the analysed dialogues.",
            "learned_vocab": "Vocabulary that appears 12 times or more, as per Nation (2014)",
            "acq_index": "The ratio of learned vocabulary (vocab appearing 12 or more times) to the amount of total unique vocabulary.",
            "pv": "Phrasal verbs are traditionally understood as made up of a verb and an adverbial particle (Riguel, 2014), examples include 'make up', 'shut down', 'give up'.",
            "slang": "The amount of words filtered out by my own (limited) slang filter.",
            "lexical_prop": "As per Johansson (2008), lexical items include nouns (thing), verbs (to do), adjectives (fast) and adverbs (quickly). This measures the ratio of these lexical items AND proper nouns (London, Toyota) to all words in a given text.",
            "lexical_no_prop": "Lexical density (explained above), but without proper nouns.",
            "passives": "Passive voice example = 'The mat was sat on by the cat', as opposed to active voice: 'The cat sat on the mat' (Source: https://developers.google.com/tech-writing/one/active-voice, accessed 29 april 2026).",
            "subordinates": "Basically a sentence within another sentence, stuff like: 'The dog barked WHEN THE MAILMAN ARRIVED' or 'He read his book WHILE HE WAS WAITING'",
            "conditionals": "Basically sentences that have a condition in them, 'IF it rains I'll wear a coat' or 'I would be a basketball player IF I was taller'.",
            "ttr": "Type to Token Ratio - dividing the amount of UNIQUE words (a unique word is a type) by ALL the words (a word is a token), though it generally lower the longer a text is (Richards, 1987), because if you have an extremely long book then even rare words start repeating",
            "mtld": "Another measure for text diversity, but way less dependent on text length (McCarthy & Jarvis, 2010).",
            "t95": "This shows what CEFR level you have to be at to 'understand' a given game. According to Laufer (1995), to understand a text you need to understand 95% of the words in the text. This might be lower in video games, as they're rich in context that helps in understanding words (Shahiwala & Rahul, 2025).",
            "t98": "This shows what CEFR level you have to be at to 'acquire' new language from a given game. According to Hu & Nation (2000), to acquire language from a text you need to understand 98% of the words in the text. This might be lower in video games, as they're rich in context that helps in understanding words (Shahiwala & Rahul, 2025).",
            "u95": "The same as above, but for unique vocabulary.",
            "u98": "The same as above, but for unique vocabulary.",
            "fre": "206.835 − (1.015 × average_words_sentence) − (84.6 × average_syllables_word), as per Eleyan, Othman and Eleyan (2020).",
            "fkg": "(0.39 × average_words_sentence) + (11.8 × average_syllables_word) − 15.9, as per Eleyan, Othman and Eleyan (2020).",
            "smog": "1.043 * sqrt(30 * (polysyllabic words / sentences)) + 3.1291, as per Zhou, Jeong and Green (2017).",
            "dale": "Raw Score = 0.1579 * (difficult_words / total_words * 100) + 0.0496 * (total_words / total_sentences)",
            "top_lemmas": "Lemmas (the base forms of a word) that appear the most often in the dialogues.",
            "top_bigrams": "Bigrams (combinations of 2 words) that appear the most often in the dialogues.",
            "verb_prep": "Combinations of verb-preposition (eg. depend on, apply for, agree with) that appear the most often in the dialogues.",
            "adj_noun": "Combinations of adjective-noun (eg. fast dog, iron sword, legendary hero) that appear the most often in the dialogues.",
            "phrasal_verbs": "Phrasal verbs (verb + adverbial particle, eg. 'make up', 'shut down', as per Riguel, 2014) that appear the most often in dialogues.",
            "oov_rate": "The amount of words that were not in the English dictionary i used (spaCy en_web_core_md) divided by the amount of total words.",
            "top_oov": "Out-of-Vocabulary words that appeared the most often."
        }
    },
    "pl": {
        "nav": {
            "home": "Strona Główna",
            "dashboard": "Język w Grach Wideo"
        },
        "controls": {
            "music_on": "Włącz muzykę",
            "music_off": "Wyłącz muzykę",
            "theme": "Jasny/Ciemny",
            "lang": "Change to English 🇬🇧",
            "attribution": "Teraz gra: \"Bolero\" Maurice'a Ravela w wykonaniu Orkiestry Lamoureux"
        },
        "about": {
            "title": "O Mnie",
            "p1": "Hejka! Jestem 21-letnim studentem <a href='https://sylabusy.agh.edu.pl/pl/1/2/19/1/1/0/81'>informatyki społecznej AGH</a> (chociaż już właściwie kończę 1 stopień). Od kiedy pamiętam byłem bardzo zainteresowany tym, jak ludzie wchodzą w interakcję z komputerami - mega dużo czasu spędziłem czytając o urządzeniach peryferyjnych, aż do momentu kiedy zrobiłem <a href='https://github.com/Kamillon125/bonk/blob/gh-pages/index.md'>własny układ klawiatury</a> (!!! jest to bardzo bezużyteczne, ale również fajne!). Urządzenia peryferyjne to nie wszystkie rzeczy około-człowieko-komputerowe, którymi się interesowałem - przez długi czas ciekawiłem się przenośnymi konsolami (i tym, jak zmieniały się na przestrzeni czasu), co, znowu, nie jest może najbardziej użyteczne i produktywne, ale mega mnie interesowało. Innym moim zainteresowaniem jest językoznawstwo, a w szczególności ta część językoznawstwa, która odnosi się do uczenia się języków obcych. Znam polski, angielski (C2), przeczytałem po ukraińsku książkę w 2024 (Лаовай Kateryny Kulyk), a od jakiegoś czasu zacząłem powolutku pracę nad włoskim. Jeśli wszystko się uda, to do końca 2026 będę miał opublikowany artykuł naukowy o przyswajaniu języków obcych w grach wideo. Kiedyś byłem BARDZO dużym fanem Nintendo (był to błąd) i w tamtym okresie przeszedłem właściwie wszystkie Pokemony i Zeldy, jakie tylko istniały. Wciąż bardzo lubię wracać do tych gier, szczególnie ze względu na ich klimat i vibe (całkowicie zgadzam się z <a href='https://www.youtube.com/watch?v=xI43wgrPP28'>Internet Pitstop</a>, jeśli chodzi o klimat w grach) Jeżeli chcesz się dowiedzieć więcej o moich rzeczach zawodowych, to tutaj jest <a href='https://www.linkedin.com/in/kamil-niewiarowski/'>LinkedIn</a>, tutaj tych rzeczy nie ma."
        },
        "computer": {
            "title": "Komputer",
            "p1": "Po wielu latach próbowania odejścia od Windowsa wreszcie mi się to (chyba) udało. Nie podoba mi się to, że MS Windows staje się po prostu coraz gorszy - szczerze nie chcę, żeby ktokolwiek wpychał mi do gardła Copilot, ani żeby mój system operacyjny korzystał z moich danych w większym stopniu, niż ja korzystam z mojego systemu operacyjnego. Wciąż mam gdzieś w komputerze system Windows, ale nie używam go właściwie nigdy (jest tylko w razie potrzeby, gdybym jakichś programów nie mógł odpalić na Linuxie). Obecnie korzystam z <a href='https://cachyos.org/'>CachyOS</a> ze środowiskiem <a href='https://www.gnome.org/'>Gnome</a>. Próbowałem <a href='https://system76.com/cosmic'>COSMIC</a>, ale był zbyt nowy i trochę rzeczy na nim nie działało. Próbowałem również <a href='https://kde.org/'>KDE</a>, który był całkiem git, ale nie podobał mi się wizualnie. Poza tym kiedyś używałem tiling window managera (<a href='https://github.com/WillPower3309/swayfx'>swayfx</a>), ale szczerze nie miałem siły konfigurować dosłownie wszystkiego od podstaw, i wolałem lekko dostosować Gnome do swoich potrzeb. W sumie bardzo polecam Linuxa - zdecydowana większość rzeczy działa, nawet gry działają na karcie Nvidii (którą mam), a jeśli chodzi o gry multiplayer z antycheatem które nie działają (np Valorant), to tak właściwie to jest plus Linuxa, że nie mogę na nim grać w Valorant."
        },
        "games": {
            "title": "Gry wideo",
            "p1": "Gram właściwie od dziecka, ale mam kilka wspomnień związanych z grami, które są dla mnie szczególnie spoko. I nie mówię tutaj o jakichś sukcesach w grach kompetetywnych, bo nawet jeśli uznamy bycie top 1 na świecie za sukces, to z mojej perspektywy to wspomnienie po prostu znikło i nie ma już dla mnie żadnego znaczenia. To, co ma znaczenie, to wspomnienia związane z konkretnymi sytuacjami - pamiętam, jak grałem w swoje pierwsze Pokemony (Pokemon X) przez święta Bożego narodzenia, i jak tuż po Wigilii łapałem Mewtwo, oraz jak bardzo ten proces ułatwił Venusaur. Pamiętam również, jak podczas swoich matur ogrywałem po raz pierwszy Tears of The Kingdom - grę, która wzbudziła we mnie zainteresowanie Zeldą, i grę, przez którą następne dwa lata poświęciłem na granie we wszystkie Zeldy, które tylko mogłem znaleźć. Pamiętam wreszcie, jak po raz pierwszy w wieku 7 lat grałem w Minecrafta w wakacje i budowałem swoją pierwszą bazę wewnątrz minecraftowej góry. Jedno podsumowanie, które tutaj mam, to to, że moje ulubione gry wideo to nie najlepsze gry wideo, w jakie grałem - to gry wideo, w jakie grałem w najlepszych sytuacjach."
        },
        "music": {
            "title": "Muzyka",
            "p1": "Generalnie to im dłużej żyję na tym świecie, tym bardziej podoba mi się rap, i nie wiem, co z tym fantem zrobić. Ostatnio sporo słucham <a href='https://tacohemingway.com'>Taco</a>, w szczególności <a href='https://open.spotify.com/album/6sIS875clsC3HlnRhIzXWL'>\"LATARNIE WSZĘDZIE DAWNO ZGASŁY\"</a> i podoba mi się to, że przy każdym przesłuchaniu znajduję jakieś nowe smaczki. Ale tak całkowicie szczerze to muzyki słucham bardzo niewiele, właściwie tylko kiedy jadę autobusem, więc i na rap nie poświęcam dużo czasu."
        },
        "dashboard": {
            "series": "Seria",
            "year": "Rok",
            "source": "Źródło",
            "type": "Typ",
            "completeness": "Kompletność",
            "voiceover": "Dubbing",
            "total_lines": "Suma Linii Dialogowych",
            "word_count": "Liczba Słów",
            "sentence_count": "Liczba Zdań",
            "tier1_title": "1. Użyteczność w Uczeniu",
            "tier1_desc": "Wykresy słupkowe porównujące ilość unikalnych słów oraz unikalnych słów przyswojonych (takich, które pojawiły się 12 lub więcej razy) w grze wideo z medianą korpusu.",
            "unique_vocab": "Unikalne Słownictwo",
            "learned_vocab": "Przyswojone Słownictwo",
            "learned_b2": "B2 Przyswojone",
            "learned_c1": "C1 Przyswojone",
            "learned_c2": "C2 Przyswojone",
            "tier2a_title": "2A. Metryki Składni i Leksyki",
            "tier2a_desc": "Różne metryki mierzące kwestie składniowe (gramatyczne) i leksykalne (związane ze słownictwem).",
            "pv_1k": "Czasowniki Złożone (na 1k)",
            "slang_dens": "Zagęszczenie Slangu",
            "lex_with": "Gęstość Leksykalna (z Własnymi)",
            "lex_without": "Gęstość Leksykalna (bez Własnych)",
            "passives": "Strona Bierna/Zdanie",
            "subordinates": "Zdania Podrzędne/Zdanie",
            "conditionals": "Tryby Warunkowe/Zdanie",
            "tier2b_title": "2B. Rozkład Poziomów CEFR",
            "tier2b_desc": "Wykres słupkowy z dwiema osiami...",
            "tier3a_title": "3A. Progi (Thresholds)",
            "tier3a_desc": "Wskazuje, na jakim poziomie językowym musisz być, aby zrozumieć tekst (95% znanych słów, Laufer (1995)) lub przyswoić nowe słowa (98% znanych słów, Hu & Nation, 2000). Logiczne jest jednak, że te progi mogą być niższe w grach wideo (gdzie można polegać na kontekście bardziej niż w książkach).",
            "tier3b_title": "3B. Zdania CEFR",
            "tier3b_desc": "Użyłem modelu huggingface.co/dksysd/cefr-classifier, aby sklasyfikować każde zdanie do odpowiedniego poziomu CEFR. Klasyfikator ten radzi sobie całkiem nieźle, osiągając 89,7% dokładności na zbiorze danych korpusu równoległego.",
            "level": "Poziom",
            "count": "Liczba",
            "tier3c_title": "3C. Czytelność (L1)",
            "tier3c_desc": "Różne metryki czytelności tekstu w grze. Są ważniejsze dla osób, których ojczystym językiem jest angielski, ale wciąż dość interesujące.",
            "tier4a_title": "4A. Najczęstsze Formy",
            "tier4a_desc": "Pokazuje najczęściej pojawiające się lematy, bigramy, czasowniki złożone (phrasal verbs) oraz kombinacje czasownik-przyimek i przymiotnik-rzeczownik.",
            "top_lemmas": "Lematy",
            "top_bigrams": "Bigramy",
            "verb_prep": "Czasownik-Przyimek",
            "adj_noun": "Przymiotnik-Rzecz",
            "phrasal_verbs": "Czasowniki Złożone",
            "tier4b_title": "4B. OOV (Poza Słownikiem)",
            "tier4b_desc": "Słowa spoza słownika (Out of vocabulary) to w zasadzie słowa, które pojawiły się w grze, ale nie było ich w słowniku angielskim, którego użyłem (spaCy en_core_web_md).",
            "oov_rate": "Wskaźnik OOV",
            "top_10_oov": "Top 10 OOV",
            "toggle_oov": "Przełącz Pełną Listę OOV",
            "global_summary": "W sumie: <strong>702 862</strong> pobranych linijek dialogowych z <strong>56</strong> gier, przeanalizowano <strong>1 333 761</strong> zdań składających się z <strong>9 029 776</strong> słów.",
            "methodology_title": "Metodologia i Notatki",
            "methodology_desc": "Wszystkie okładki gier wideo, tytuły i powiązane z nimi obrazy są własnością ich wydawców i deweloperów..."
        },
        "tooltips": {
            "placeholder": "[Miejsce na wyjaśnienie. Edytuj w content.js]",
            "source": "Dane zebrane z Video Game Dialogue Corpus (Rennick & Roberts, w druku). Źródło to miejsce, z którego pobrano dane dialogowe.",
            "type": "Dane zebrane z Video Game Dialogue Corpus (Rennick & Roberts, w druku). Typ określa rodzaj źródła: czy zostało stworzone przez fanów, jest oficjalne, wydobyte z plików gry itp.",
            "completeness": "Dane zebrane z Video Game Dialogue Corpus (Rennick & Roberts, w druku). Kompletność określa, jak pełny jest zbiór dialogów. Skala obejmuje próbkę (sample - tylko część dialogów), w toku (in progress), aż po wysoki (high) i kompletny (complete).",
            "voiceover": "Dane zebrane na potrzeby tego projektu – określają, czy gra posiadała jakąś formę dubbingu (voiceover), co może ułatwiać zrozumienie, zgodnie z teorią podwójnego kodowania (dual coding theory) (Mayer & Sims, 1994). Wartości wahają się od brak (none) i minimalny (minimal) aż do pełny (full).",
            "total_lines": "Całkowita liczba linii wyekstrahowanych ze zbioru danych gry, nie obejmująca rzeczy takich jak opisy twórców solucji (jeśli źródłem był poradnik).",
            "word_count": "Całkowita liczba słów w grze, wliczając cały tekst dialogów.",
            "sentence_count": "Liczba zdań w grze, wykryta przez narzędzie Sentencizer z biblioteki spaCy.",
            "unique_vocab": "Ilość unikalnego słownictwa w analizowanych dialogach.",
            "learned_vocab": "Słownictwo, które pojawia się 12 lub więcej razy, zgodnie z Nation (2014).",
            "acq_index": "Stosunek przyswojonego słownictwa (słowa pojawiające się 12 lub więcej razy) do całkowitej ilości unikalnych słów.",
            "pv": "Czasowniki złożone (phrasal verbs) są tradycyjnie rozumiane jako złożone z czasownika i partykuły przysłówkowej (Riguel, 2014), przykłady to 'make up', 'shut down', 'give up'.",
            "slang": "Ilość słów przefiltrowanych przez mój własny (ograniczony) filtr slangu.",
            "lexical_prop": "Według Johansson (2008) jednostki leksykalne obejmują rzeczowniki (thing), czasowniki (to do), przymiotniki (fast) i przysłówki (quickly). Mierzy to stosunek tych jednostek leksykalnych ORAZ nazw własnych (London, Toyota) do wszystkich słów w danym tekście.",
            "lexical_no_prop": "Gęstość leksykalna (wyjaśniona powyżej), ale bez nazw własnych.",
            "passives": "Przykład strony biernej: 'The mat was sat on by the cat', w przeciwieństwie do strony czynnej: 'The cat sat on the mat' (Źródło: https://developers.google.com/tech-writing/one/active-voice, dostęp 29 kwietnia 2026).",
            "subordinates": "Zasadniczo zdanie wewnątrz innego zdania, np.: 'The dog barked WHEN THE MAILMAN ARRIVED' lub 'He read his book WHILE HE WAS WAITING'.",
            "conditionals": "Zdania zawierające warunek, np.: 'IF it rains I'll wear a coat' lub 'I would be a basketball player IF I was taller'.",
            "ttr": "Type to Token Ratio (Wskaźnik Typu do Tokenu) – podzielenie liczby UNIKALNYCH słów (unikalne słowo to typ - 'type') przez WSZYSTKIE słowa (słowo to token), choć wskaźnik ten zazwyczaj maleje im dłuższy jest tekst (Richards, 1987), ponieważ w bardzo długiej książce nawet rzadkie słowa zaczynają się powtarzać.",
            "mtld": "Kolejna miara różnorodności tekstu, ale w znacznie mniejszym stopniu zależna od jego długości (McCarthy & Jarvis, 2010).",
            "t95": "Wskazuje to, na jakim poziomie CEFR musisz być, aby 'zrozumieć' daną grę. Według Laufer (1995), aby zrozumieć tekst, musisz znać 95% zawartych w nim słów. Może to być niższa wartość w grach wideo, ponieważ są one bogate w kontekst, który pomaga w zrozumieniu słów (Shahiwala & Rahul, 2025).",
            "t98": "Wskazuje to, na jakim poziomie CEFR musisz być, aby 'przyswoić' nowy język z danej gry. Według Hu & Nation (2000), aby przyswoić język z tekstu, musisz znać 98% zawartych w nim słów. Wartość ta może być niższa w grach wideo ze względu na kontekst pomagający w zrozumieniu słów (Shahiwala & Rahul, 2025).",
            "u95": "To samo co powyżej, ale dla unikalnego słownictwa.",
            "u98": "To samo co powyżej, ale dla unikalnego słownictwa.",
            "fre": "206.835 − (1.015 × średnia_liczba_słów_w_zdaniu) − (84.6 × średnia_liczba_sylab_w_słowie), zgodnie z Eleyan, Othman i Eleyan (2020).",
            "fkg": "(0.39 × średnia_liczba_słów_w_zdaniu) + (11.8 × średnia_liczba_sylab_w_słowie) − 15.9, zgodnie z Eleyan, Othman i Eleyan (2020).",
            "smog": "1.043 * sqrt(30 * (słowa_wielosylabowe / zdania)) + 3.1291, zgodnie z Zhou, Jeong i Green (2017).",
            "dale": "Wynik surowy = 0.1579 * (trudne_słowa / wszystkie_słowa * 100) + 0.0496 * (wszystkie_słowa / wszystkie_zdania)",
            "top_lemmas": "Lematy (podstawowe formy słowa), które pojawiają się najczęściej w dialogach.",
            "top_bigrams": "Bigramy (kombinacje 2 słów), które pojawiają się najczęściej w dialogach.",
            "verb_prep": "Kombinacje czasownik-przyimek (np. depend on, apply for, agree with), które pojawiają się najczęściej w dialogach.",
            "adj_noun": "Kombinacje przymiotnik-rzeczownik (np. fast dog, iron sword, legendary hero), które pojawiają się najczęściej w dialogach.",
            "phrasal_verbs": "Czasowniki złożone (czasownik + partykuła przysłówkowa, np. 'make up', 'shut down', zgodnie z Riguel, 2014), które pojawiają się najczęściej w dialogach.",
            "oov_rate": "Liczba słów, których nie było w użytym przeze mnie słowniku języka angielskiego (spaCy en_core_web_md), podzielona przez całkowitą liczbę słów.",
            "top_oov": "Najczęściej pojawiające się słowa spoza słownika (Out-of-Vocabulary)."
        }
    }
};
